name: tests
on: push

jobs:
  hadolint:
    name: image docker
    runs-on: ubuntu-latest  
    container: hadolint/hadolint
    steps:
    - uses: actions/checkout@v1
        run: hadolint Dockerfile